print("############################## ")
print("#                            # ")
print("#    Ajeng Diah Pramesti     # ")
print("#       2210817220001        # ")
print("#                            # ")
print("############################## ")